# Deployment da aplicação web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-peso
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: conversao-peso
  template:
    metadata:
      labels:
        app: conversao-peso
    spec:
      containers:
        - name: conversao-peso
          image: ghcr.io/claudi0s0uza/conversao-peso
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports: 
            - containerPort: 80
--- 
# Service da aplicação web
apiVersion: v1
kind: Service
metadata:
  name: conversao-peso
spec: 
  selector:
    app: conversao-peso
  ports:
    - port: 80
      protocol: TCP
      name: http
      nodePort: 30050
  type: LoadBalancer
